config/routes.rb
Rails.application.routes.draw do
  root 'feedbacks#new'

  resources :feedbacks, only: %i[new create show]

  namespace :admin do
    get '/', to: 'feedbacks#index'
    resources :feedbacks, only: %i[destroy]
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  extend TimeSplitter::Accessors
  validate :age_check, :name_check, :date_check
  mount_uploader :attachment, AttachmentUploader
  split_accessor :date

  private

  def name_check
    words = name.split(' ')
    capitalized_words = false
    words.each do |word|
      capitalized_words = word =~ /^[A-ZА-Я'][a-zа-я\-' ]+[a-zа-я']?$/u ? true : false
    end
    errors.add(:name, :capitalized_words_validation) if words.length != 2 || !capitalized_words
  end

  def age_check
    return if birthday.present? && birthday <= 17.years.ago && birthday >= 65.years.ago
    errors.add(:birthday, :age_validation)
  end

  def date_check
    return if date.present? && date > Time.zone.now
    errors.add(:date, :date_validation)
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/admin/feedbacks_controller.rb
module Admin
  class FeedbacksController < ApplicationController
    def index
      @feedbacks = Feedback.all
    end

    def show
      @feedback = Feedback.find(params[:id])
    end

    def destroy
      @feedback = Feedback.find(params[:id])
      @feedback.destroy
      redirect_to admin_path, notice: 'Резюме было успешно удалено'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedbacks = Feedback.all
  end

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      flash[:success] = "Мы ждем вас в #{@feedback.date}"
      redirect_to @feedback
      # redirect_to feedbacks_path, notice: "The feedback from #{@feedback.name} has been uploaded."
    else
      render :new
    end
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :birthday, :date_date, :date_time, :attachment)
  end
end

app/views/admin/feedbacks/index.html.haml
- unless flash[:notice].blank?
  .alert.alert-info.alert-dismissible
    %button.close{ 'aria-hidden' => 'true', 'data-dismiss' => 'alert', :type => 'button' } ×
    = flash[:notice]

%h3
  Feedbacks list
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th Download Link
      %th Meeting Time
      %th
  %tbody
    - @feedbacks.each do |feedback|
      %tr
        %td= feedback.name
        %td= link_to 'Download Resume', feedback.attachment_url
        %td= feedback.date.strftime('%H:%M %m/%d/%Y')
        %td= button_to 'Delete', admin_feedback_path(feedback), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure that you wish to delete #{feedback.name}?" }

app/views/feedbacks/new.html.haml
.register-box
  .register-logo
    %a{ href: '/' }
      %b> Feedback
      form
  .feedback-box-body
    %p.feedback-box-msg Введите данные
    = simple_form_for @feedback do |f|
      - unless @feedback.errors.empty?
        .alert.alert-danger.alert-dismissible
          %button.close{ 'aria-hidden' => 'true', 'data-dismiss' => 'alert', :type => 'button' } ×
          = f.error_notification
          %ul
          - @feedback.errors.full_messages.each do |msg|
            %li= msg
      .form-group
        = f.label t(:name)
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label t(:birthday)
        .input-group
          .input-group-addon
            %i.fa.fa-calendar
          = f.text_field :birthday, id: 'datemask', class: 'form-control'
      .form-group
        = f.label t(:date)
        .input-group
          .input-group-addon
            %i.fa.fa-calendar
          = f.text_field :date_date, id: 'date', class: 'form-control'
        .input-group
          .input-group-addon
            %i.fa.fa-clock-o
          = f.text_field :date_time, id: 'time', class: 'form-control'
      .form-group
        = f.label :attachment
        = f.file_field :attachment
      .row
        .col-xs-6.pull-right
          = f.submit t(:submit), class: 'btn btn-primary btn-block btn-flat'

= javascript_include_tag 'feedbacks'

app/views/feedbacks/show.html.haml
- meeting_time = @feedback.date.strftime('%H:%M %m/%d/%Y')
.callout.callout-info{:style => "margin-bottom: 0!important;"}
  %h4
    Спасибо за отклик:
  = "Мы ждем Вас в #{meeting_time}"

app/views/layouts/_head.html.haml
%head
  %title FeedbackForm
  %meta{ charset: 'utf-8' }
  %meta{ content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no', name: 'viewport' }
  %meta{ content: '', name: 'keyword' }
  %link{ rel: 'icon', type: 'image/vnd.microsoft.icon', href: '/favicon.ico' }
  %link{ href: 'https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', rel: 'stylesheet', type: 'text/css' }
  = stylesheet_link_tag  'application', media: 'all'
  / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
  / WARNING: Respond.js doesn't work if you view the page via file://
  /[if lt IE 9]
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  = javascript_include_tag 'application', media: 'all'
  = csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body.hold-transition.background-page
    = yield